const DEFAULT_HEADERS = {
    'X-XSS-Protection': '1; mode=block',
    'X-Content-Type-Options': 'nosniff',
    'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, GET, PUT, DELETE, PATCH, OPTIONS',
    'Access-Control-Allow-Headers': 'Cache-Control, Content-Type, Authorization, X-Force-Clear-Cache',
};

/**
 * @constant
 */
const MIME_TYPES = {
    'html': 'text/html',
    'css': 'text/css',
    'js': 'application/javascript',
    'json': 'application/json',
    'xml': 'application/xml',
    'png': 'image/png',
    'jpg': 'image/jpeg',
    'gif': 'image/gif',
    'bmp': 'image/bmp',
    'ico': 'image/x-icon',
    'tif': 'image/tiff',
    'svg': 'image/svg+xml',
    'zip': 'application/zip',
    'rar': 'application/x-rar-compressed',
    '7z': 'application/x-7z-compressed',
    'gz': 'application/gzip',
    'bz2': 'application/x-bzip2',
    'pdf': 'application/pdf',
    'rtf': 'application/rtf',
    'doc': 'application/msword',
    'xls': 'application/vnd.ms-excel',
    'ppt': 'application/vnd.ms-powerpoint',
    'odt': 'application/vnd.oasis.opendocument.text',
    'ods': 'application/vnd.oasis.opendocument.spreadsheet',
    'txt': 'text/plain',
    'csv': 'text/csv',
    'wav': 'audio/wav',
    'mp3': 'audio/mpeg',
    'mp4': 'video/mp4',
    'avi': 'video/x-msvideo',
    'mkv': 'video/x-matroska',
    'mov': 'video/quicktime',
    'swf': 'application/x-shockwave-flash',
    'aif': 'audio/x-aiff',
    'mid': 'audio/midi',
    'flac': 'audio/flac',
    'wma': 'audio/x-ms-wma',
    '3gp': 'video/3gpp',
    'mpe': 'video/mpeg',
    'm4v': 'video/x-m4v',
    'bin': 'application/octet-stream',
    'deb': 'application/octet-stream',
    'img': 'application/octet-stream',
    'msp': 'application/octet-stream',
    'apk': 'application/vnd.android.package-archive',
    'bat': 'application/x-msdownload',
    'csh': 'application/x-csh',
    'jar': 'application/java-archive',
    'prc': 'application/x-mobipocket-ebook',
    'rpm': 'application/x-redhat-package-manager',
    'sea': 'application/x-sea',
    'tcl': 'application/x-tcl',
    'xpi': 'application/x-xpinstall',
    'xhtml': 'application/xhtml+xml',
    'xspf': 'application/xspf+xml',
    'sql': 'application/sql',
    'tar': 'application/x-tar',
    'php': 'application/x-httpd-php',
    'jsp': 'text/html',
    'tsv': 'text/tab-separated-values',
    'ics': 'text/calendar',
    'hwp': 'application/vnd.hancom.hwp',
    'wasm': 'application/wasm',
    'yaml': 'application/x-yaml',
    'ai': 'application/postscript',
    'ttf': 'font/ttf',
    'woff': 'font/woff',
    'eot': 'application/vnd.ms-fontobject',
    'psd': 'image/vnd.adobe.photoshop',
    'indd': 'application/x-indesign',
    'raw': 'image/x-raw',
    'oga': 'audio/ogg',
    'opus': 'audio/opus',
    'weba': 'audio/webm',
    'caf': 'audio/x-caf',
    'ra': 'audio/vnd.rn-realaudio',
    'ogv': 'video/ogg',
    'webp': 'image/webp',
    'qt': 'video/quicktime',
    'rm': 'application/vnd.rn-realmedia',
    'rmvb': 'application/vnd.rn-realmedia-vbr',
};

module.exports = {
    DEFAULT_HEADERS,
    MIME_TYPES,
}